# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ls ~/.ssh/
  - echo $SECURE_KEY

install:
  - ./travis-tool.sh github_package s-u/PKI
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - secure: u7HuwKR6poyF0hZNZUm0705UFt7toWD8MVV1NlTZ/c6Os760oBCgMwSnOeo1gmRO+ho8uWRClYX3vnpf/rn+Sokxx4MkKq8MIo00PD7216EKjGZ/tyaopEz6bxZCOaMCjoGsvkv975lkPe1NuXk22RSvxvZrqwKGcx7FJ0bUvxQ=
